'use strict'

module.exports = {
  DEFAULT_TEMP: 15,
  DEFAULT_MAX_ITERATIONS: 5000,
  DEFAULT_NEIGHBOR_EXECUTIONS: 100,
  DEFAULT_RUNS: 30,
  COOLING_RATE: 1 - 0.003,
  LOWEST_TEMP: 0.01,
  GAP_SYMBOL: '-',
  GAP_SYMBOL_PENALTY: 5,
  PROBABILITY_ADD_DELETION: 0.45,
  PROBABILITY_REMOVE_DELETION: 0.9,
  PROBABILITY_POSITION_HEAD: 0.33,
  PROBABILITY_POSITION_TRAIL: 0.66,
}
