'use strict'

module.exports = {
  DEFAULT_TEMP: 20,
  DEFAULT_MAX_ITERATIONS: 5000,
  DEFAULT_NEIGHBOR_EXECUTIONS: 10,
  DEFAULT_RUNS: 30,
  COOLING_RATE: 1 - 0.003,
  LOWEST_TEMP: 0.003,
  GAP_SYMBOL: '-',
  GAP_SYMBOL_PENALTY: 1,
  ALL_GAP_SYMBOL_PENALTY: 2,
  PROBABILITY_ADD_DELETION: 0.33,
  PROBABILITY_REMOVE_DELETION: 0.66,
  PROBABILITY_POSITION_HEAD: 0.33,
  PROBABILITY_POSITION_TRAIL: 0.66,
}
